name: Pryv app-web-auth3 deployment workflow

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13]

    steps:
      - name: Download master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js with version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to the docker containers registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
          username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
          password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

      - name: Download base image and change the tag
        run: |
          docker pull ${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.5.1
          docker tag "${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.5.1" "pryvio/base:1.5.1"

      - name: Get latest git tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
        id: get-latest-tag

      - name: Npm packages installation
        run: yarn install

      - name: Login to the docker hub containers registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_PRYV_USERNAME_DOCKERHUB }}
          password: ${{ secrets.REGISTRY_PRYV_PASSWORD_DOCKERHUB }}

      - name: Build image
        run: cd ./build && docker build --rm -f Dockerfile -t ${{ secrets.REGISTRY_PRYV_SERVER_DOCKERHUB }}/pryvio/app-web-auth3:${{ steps.get-latest-tag.outputs.tag }} ./..

      - name: upload new image to Docker Hub
        run: docker push ${{ secrets.REGISTRY_PRYV_SERVER_DOCKERHUB }}/pryvio/app-web-auth3:${{ steps.get-latest-tag.outputs.tag }}
